name: build and deploy Automation rules
resources:
 pipelines:
   - pipeline: Scripts
     source: 'buildScripts'

trigger:
 paths:
   include:
     - AutomationRules/*

stages:
- stage: build_automationrules

  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'vs2017-win2016'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy Automation rules'
         inputs:
          SourceFolder: AutomationRules
          TargetFolder: '$(Pipeline.Workspace)'
       - task: Files-Validator@1
         inputs:
           rootDir: '$(Pipeline.Workspace)/*.json'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: AutomationRules'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)'
          ArtifactName: AutomationRules

- stage: deploy_automationrules
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-2019'
      variables: 
      - group: madesous-3
      steps:
      - download: current
        artifact: AutomationRules
      - download: Scripts
        patterns: '*.ps1'
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'devopssentinel'
          subscriptionId: '036f021c-23f2-4483-a1c5-adc28edcabc1'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'cicd'
          location: 'West Europe'
          templateLocation: 'URL of the file'
          csmFileLink: 'https://raw.githubusercontent.com/mariavaladas/sentinelascode/master/AutomationRules/automationrule01'
          overrideParameters: '-workspace $(Workspace)'
          deploymentMode: 'Incremental'


          